default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: 127.0.0.1

development:
  <<: *default
  database: k8s_rails

test:
  <<: *default
  database: k8s_rails_test

production:
  <<: *default
  database: k8s_rails_production
  username: root
  password: password
  host: 10.108.98.196
