name: Github Action CI

on:
  push:
    branches: [ master ]
env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/rails-sample:dummy
  # IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/rails-sample:${{ github.run_number }}

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Push Docker image
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     push: true
      #     tags: |
      #       ${{ env.IMAGE_NAME }}
      #       ghcr.io/${{ github.repository_owner }}/rails-sample:dummy
      #     file: docker/rails/Dockerfile
      #     secrets: |
      #       "RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}"

      - name: Push remote
        # uses: actions/checkout@v2
        run: |
          git config user.name thr3a
          git config user.email thr3a@example.com
          git clone https://${{secrets.MANIFEST_TOKEN}}@github.com/thr3a/kubernetes-rails-sample-manifests /tmp/app
          cd /tmp/app
          yq '.spec.template.spec.containers[0].image = "${{ env.IMAGE_NAME }}"' deployment.yaml -i
          git add .
          git commit -m "update: ${{ env.IMAGE_NAME }}"
          git push


      # - name: Change Pod Name
      #   run: |
      #     echo -e "machine github.com\nlogin ${{ secrets.GITHUBUSER }}\npassword ${{ secrets.GITHUBTOKEN }}" > ~/.netrc
      #     git config --global user.email ${{ secrets.EMAIL }}
      #     git config --global user.name ${{ secrets.GITHUBUSER }}
      #     git clone https://github.com/${{ secrets.GITHUBUSER }}/config.git
      #     cd config/manifest
      #     yq e '.metadata.name = "gitops-deployment${{ github.run_number }}"' -i app.yaml
      #     git add app.yaml
      #     git commit -m ${{ github.run_number }} -a
      #     git push origin main
